import { clean, isChronological, parseAmount, roundMoney } from "./common.js";
import { correctDebitCreditByBalance } from "../validation.js";
import { reconstructTransactions } from "../ocrTransactionReconstructor.js";

// This layout is a Finacle ("Universal Banking Solution from Infosys") core-banking
// "Transaction Inquiry" screen print, used by several Indian banks (IDBI included) as a
// scanned/photocopied statement in place of the bank's own printed statement layout. It has a
// different table shape than the bank-specific net-banking statement parsers (idbiParser.js
// etc.), so it's detected and parsed independently, generalized to the screen's column set
// rather than any single bank's branding.
//
// Parsing is delegated to ocrTransactionReconstructor.js's date-boundary block reconstruction
// rather than reading OCR word x-coordinates: on a low-quality photocopy, word/line bounding
// boxes are frequently unreliable, and requiring two specific date columns to land on the same
// OCR-clustered line (the previous approach) meant a single misclustered line could cascade into
// merging several transactions into one row. Any line that *starts* with a date is enough to
// open a new transaction here, which tolerates that kind of OCR noise far better.
// "Finacle" and "Universal Banking Solution from Infosys" are stylized logo/tagline text (not
// plain table text), so a low-quality scan's OCR pass mangles them far more often than it mangles
// the screen's actual column headers -- e.g. one real sample OCR'd "Finacle" as "mn Fi 3 le" and
// "from Infosys" as "fre info 5". Requiring those exact phrases made detection fail on scans that
// were otherwise perfectly readable, silently dropping the PDF to the generic OCR parser (which
// merges rows instead of respecting this screen's table shape). The structural markers below --
// this screen's own column headers plus its date-leading transaction rows -- survive OCR far more
// reliably and are, together, already unique enough to this layout without the brand text.
function isFinacleTransactionInquiryText(text) {
  return (
    /Transaction\s+Inquiry/i.test(text) &&
    /General\s+Ledger/i.test(text) &&
    /Withdrawal/i.test(text) &&
    /Deposit/i.test(text) &&
    /Balance/i.test(text) &&
    /Narrative/i.test(text) &&
    // OCR.space's word-level reconstruction can join a date's own tokens with spaces
    // ("28 - 03 - 2026" instead of "28-03-2026"); tolerate that here too, or detection fails on an
    // otherwise perfectly matching statement (see the matching fix in ocrTransactionReconstructor.js).
    /^\s*\d{2}\s*[/.-]\s*\d{2}\s*[/.-]\s*\d{2,4}\b/m.test(text)
  );
}

function isFinacleTransactionInquiryLayout(lines) {
  const text = lines.map((line) => clean(line.text || line)).join("\n");
  return isFinacleTransactionInquiryText(text);
}

const HEADER_FOOTER_PATTERNS = [
  /^Finacle$/i,
  /^Universal\s+Banking\s+Solution\s+from\s+Infosys/i,
  /^(Menu|Show Memo Pad|Background Menu|CCY Converter)$/i,
  /^A\/c\.\s*(ID|Name)\b/i,
  /^(General Ledger|Value|Instrument|Withdrawal|Deposit|Balance|Narrative)(\s+(Date|No\.|Amt\.))?$/i,
  // The full column-header row can arrive as one OCR line (repeated on every page); match it
  // loosely by co-occurring keywords rather than requiring an exact full-line match, since a
  // mid-document repeat of this line (page 2, 3, ...) must not get appended into a transaction's
  // narration.
  /General\s+Ledger.*Narrative/i,
  /^(Available Amt\.|Funds in Clearing|Effective Available Amt\.|Customer Status|A\/c\. Status|Purge Date|Address|City|Country|Phone|Email|State|Postal Code|Telex No\.)\b/i,
  /^CCY\/SOL ID$/i,
  /^Help$/i,
  // OCR.space's word-level reconstruction inserts a space after every token it read separately,
  // including inside a URL's own protocol ("https :// fincore.idbibank.com : 12600 / ..."). The
  // unspaced form alone let this page-footer URL slip through as ordinary content once appended
  // to whatever block happened to be open.
  /^https?\s*:\s*\/\//i,
];

const TERMINAL_PATTERNS = [/^OK$/i, /^Statement Summary\b/i, /^Statement Generated by\b/i];

// This Finacle "Transaction Inquiry" screen is an activity log ordered most-recent-first (each
// page's own header confirms this: "Page 1 of 3" leads with the latest transactions) -- the
// opposite of the chronological order an Excel statement should read in. isChronological() is
// reused here (rather than assumed) so a export that happens to already be oldest-first is left
// alone instead of being flipped backwards.
function toChronologicalOrder(transactions) {
  return isChronological(transactions) ? transactions : [...transactions].reverse();
}

// The scanned screen only ever shows a running balance *after* each transaction -- the account's
// opening balance is metadata printed elsewhere on the page (in the account-info block above the
// transaction table, not a row of the table itself), so it's captured from there (via
// extractAccountInfo, passed in as headerOpeningBalance) rather than reconstructed. The
// back-computed fallback (undo the earliest transaction's own debit/credit against its own
// balance) only kicks in if that header text wasn't legible on this particular scan -- it should
// land on the exact same value either way, since both describe the same real account state.
// Dated one day before the earliest real transaction (not the 1st of its month) so the row reads
// as "the balance the account actually opened the statement period with," giving the running
// balance a known, immediately-adjacent starting point to reconcile from.
function buildOpeningBalanceRow(firstTransaction, headerOpeningBalance) {
  const openingBalance =
    headerOpeningBalance !== null && headerOpeningBalance !== undefined
      ? headerOpeningBalance
      : roundMoney(
          Number(firstTransaction.balance || 0) + Number(firstTransaction.withdrawal || 0) - Number(firstTransaction.deposit || 0),
        );
  const date = new Date(firstTransaction.date);
  date.setUTCDate(date.getUTCDate() - 1);

  return {
    date,
    txnDate: date,
    valueDate: null,
    particulars: "Opening Balance",
    chequeNo: null,
    withdrawal: null,
    deposit: null,
    balance: openingBalance,
    // parseAmount() (used by extractAccountInfo to read the header's own "45,543.51 Cr") already
    // encodes that printed suffix as this value's sign (negative for a Dr balance) -- reading it
    // back off the sign here keeps this row's Type sourced from the same printed indicator every
    // other row's Type comes from, rather than a fresh guess.
    type: openingBalance < 0 ? "DR" : "CR",
    hadOcrCorrections: false,
    // Not a real parsed OCR row -- exempt from confidence scoring's "every transaction needs a
    // debit or credit" check, which correctly applies to actual transactions but not this one.
    isSynthetic: true,
  };
}

// The account-info block sits above the transaction table on page 1 as label/value pairs laid
// out in table cells rather than "Label: value" text, so the generic accountInfo extractor
// (which only matches colon-delimited lines) never picks it up -- this reads the handful of
// fields the "Statement of Account" export needs directly off the raw lines instead.
function extractAccountInfo(lines) {
  const text = lines.map((line) => clean(line.text || line)).join("\n");

  const accountNumber = text.match(/A\/c\.?\s*ID\s+(\S+)/i)?.[1] || null;
  const accountName = text.match(/A\/c\.?\s*Name\s+([^\n]+)/i)?.[1]?.trim() || null;
  const accountOpeningDate = text.match(/A\/c\.?\s*Opening Date\s+([\d/.-]+)/i)?.[1] || null;

  // The clean case: "Opening Balance <value> Closing Balance <value>" all in reading order.
  const balanceLine = text.match(
    /Opening Balance\s+(-?[\d,]+\.\d{2}\s*(?:Cr|Dr)?)\s+Closing Balance\s+(-?[\d,]+\.\d{2}\s*(?:Cr|Dr)?)/i,
  );
  // On a real scan, the opening-balance value and its own "Opening Balance" label can land on
  // separate reconstructed lines (the same row-clustering artifact this parser works around
  // elsewhere), with the value ending up directly before "Closing Balance" instead:
  // "45,543.51 Cr Closing Balance 1,372.11 Cr" on one line, "Opening Balance" alone on the next.
  const scatteredBalanceLine = text.match(
    /(-?[\d,]+\.\d{2}\s*(?:Cr|Dr)?)\s+Closing Balance\s+(-?[\d,]+\.\d{2}\s*(?:Cr|Dr)?)[\s\S]{0,20}Opening Balance\b/i,
  );
  const match = balanceLine || scatteredBalanceLine;

  return {
    accountNumber,
    accountName,
    accountOpeningDate,
    openingBalance: match ? parseAmount(match[1]) : null,
    closingBalance: match ? parseAmount(match[2]) : null,
  };
}

// Categorizes a transaction's narration into the same short codes a human-prepared statement
// would use, so the exported "Tran Type" column isn't just left blank. Order matters: more
// specific patterns (SMS/interest charge narrations) are checked before the generic "charge"
// catch-all so e.g. an SMS charge is labeled SMS rather than CHG.
const TRAN_TYPE_RULES = [
  [/^Int\.\s*:/i, "INT"],
  [/\bSMS[_ ]?CHARGE/i, "SMS"],
  [/\bRTGS\b/i, "RTGS"],
  [/\bNEFT\b/i, "NEFT"],
  [/\bIMPS\b/i, "IMPS"],
  [/\bUPI\b/i, "UPI"],
  [/\bBY\s+CLG\b|\bCLG\b|\bCLEARING\b/i, "CLG"],
  [/\bCHRGS?\b|\bCHARGE\b/i, "CHG"],
  [/\bTRF\b|\bTRANSFER\b/i, "TRF"],
];

function inferTranType(particulars) {
  const text = String(particulars || "");
  for (const [pattern, type] of TRAN_TYPE_RULES) {
    if (pattern.test(text)) return type;
  }
  return "MISC";
}

function withTranTypeAndType(transaction) {
  // transaction.type is already the "Cr"/"Dr" text ocrTransactionReconstructor.js's
  // buildTransaction() read directly off THIS row's own balance -- not derived from whether the
  // row itself was a debit or credit, which is a different fact (this statement's balance never
  // goes negative, so every row here reads "Cr" printed next to its balance regardless of whether
  // that particular row was a withdrawal or a deposit).
  return {
    ...transaction,
    tranType: inferTranType(transaction.particulars),
  };
}

function parseFinacleTransactions(lines, options = {}) {
  const { transactions, reviewRows } = reconstructTransactions(lines, {
    headerFooterPatterns: HEADER_FOOTER_PATTERNS,
    terminalPatterns: TERMINAL_PATTERNS,
  });

  if (options.reviewRows) options.reviewRows.push(...reviewRows);

  const accountInfo = extractAccountInfo(lines);
  const corrected = correctDebitCreditByBalance(transactions);
  const ordered = toChronologicalOrder(corrected).map(withTranTypeAndType);

  if (ordered.length > 0) {
    ordered.unshift(buildOpeningBalanceRow(ordered[0], accountInfo.openingBalance));
  }

  return { transactions: ordered, accountInfo };
}

export {
  isFinacleTransactionInquiryLayout,
  isFinacleTransactionInquiryText,
  parseFinacleTransactions,
  extractAccountInfo,
  inferTranType,
  HEADER_FOOTER_PATTERNS,
  TERMINAL_PATTERNS,
};
