import { amountItems, clean, parseDate, roundMoney } from "./common.js";
import { correctDebitCreditByBalance } from "../validation.js";

function isIdbiLayout(lines) {
  const text = lines.map((line) => clean(line.text || line)).join("\n");
  return (
    /IDBI\s+Bank\s+Ltd\.?/i.test(text) &&
    /S\.No\s+Txn Date/i.test(text) &&
    lines.some((line) => /Withdrawals\s+Deposits\s+Balance/i.test(clean(line.text || line))) &&
    lines.some((entry) => isRowStart(entry))
  );
}

function isRowStart(entry) {
  const items = entry.items || [];
  return (
    items.some((item) => /^\d+$/.test(clean(item.text)) && item.x < 60) &&
    items.some((item) => /^\d{2}\/\d{2}\/\d{4}\s+\d{2}:\d{2}:\d{2}$/.test(clean(item.text))) &&
    items.some((item) => /^\d{2}\/\d{2}\/\d{4}$/.test(clean(item.text)) && item.x > 120 && item.x < 180)
  );
}

function isNoise(text) {
  return (
    !text ||
    /^Page\s+\d+\s+of\s+\d+/i.test(text) ||
    /^IDBI Bank Ltd\./i.test(text) ||
    /^Our Toll-free/i.test(text) ||
    /^Customer Details/i.test(text) ||
    /^Branch Details/i.test(text) ||
    /^S\.No\s+Txn Date/i.test(text) ||
    /^\(Dr\)\s+\(Cr\)/i.test(text) ||
    /^Withdrawals\s+Deposits\s+Balance/i.test(text)
  );
}

function isTerminalLine(text) {
  return (
    /^Statement Summary\b/i.test(text) ||
    /^Statement Generated by\b/i.test(text) ||
    /^Legends for transactions/i.test(text) ||
    /^Important Information:/i.test(text) ||
    /^This is an account statement generated/i.test(text) ||
    /^DO NOT reply/i.test(text)
  );
}

function detectAmountColumns(lines) {
  for (const entry of lines) {
    const text = clean(entry.text || entry);
    if (!/Withdrawals\s+Deposits\s+Balance/i.test(text)) continue;
    const findX = (pattern) => (entry.items || []).find((item) => pattern.test(clean(item.text)))?.x ?? null;
    return {
      debit: findX(/^Withdrawals$/i) ?? 392,
      credit: findX(/^Deposits$/i) ?? 453,
      balance: findX(/^Balance$/i) ?? 503,
    };
  }

  return { debit: 392, credit: 453, balance: 503 };
}

function parseIdbiRow(entry, columns) {
  const items = [...(entry.items || [])].sort((left, right) => left.x - right.x);
  const sequence = Number(clean(items.find((item) => /^\d+$/.test(clean(item.text)) && item.x < 60)?.text));
  const txnDateItem = items.find((item) => /^\d{2}\/\d{2}\/\d{4}\s+\d{2}:\d{2}:\d{2}$/.test(clean(item.text)));
  const valueDateItem = items.find((item) => /^\d{2}\/\d{2}\/\d{4}$/.test(clean(item.text)) && item.x > 120 && item.x < 180);
  const date = parseDate(clean(txnDateItem?.text).slice(0, 10));
  const valueDate = parseDate(clean(valueDateItem?.text));
  const timeMatch = clean(txnDateItem?.text).match(/\b(\d{2}):(\d{2}):(\d{2})$/);
  if (date && timeMatch) {
    date.setUTCHours(Number(timeMatch[1]), Number(timeMatch[2]), Number(timeMatch[3]), 0);
  }
  if (!date || !valueDateItem) return null;

  const amounts = amountItems(items);

  // Balance: rightmost amount at or near the balance column
  const balanceItem = amounts
    .filter((item) => item.x >= columns.balance - 30)
    .sort((left, right) => right.x - left.x)[0];

  // Transaction amount: any amount between narration end and balance column
  // Use a wide range (x > 300) to catch amounts that drift slightly in later pages
  const amountItem = amounts
    .filter((item) => item !== balanceItem && item.x > 300 && item.x < (balanceItem?.x ?? columns.balance) - 5)
    .sort((left, right) => right.x - left.x)[0];
  const chequeItem = items.find(
    (item) => item.x >= 330 && item.x < 365 && /^[A-Z0-9/-]{4,}$/i.test(clean(item.text)),
  );

  const narrationEnd = chequeItem?.x ?? amountItem?.x ?? valueDateItem.x + 80;
  const narration = clean(
    items
      .filter((item) => {
        const text = clean(item.text);
        if (!text || item.x <= valueDateItem.x) return false;
        if (item === amountItem || item === balanceItem || item === chequeItem) return false;
        return item.x < narrationEnd - 5;
      })
      .map((item) => item.text)
      .join(" "),
  );

  // Determine debit vs credit by proximity to column headers
  const isDebit = amountItem
    ? Math.abs(amountItem.x - columns.debit) <= Math.abs(amountItem.x - columns.credit)
    : false;

  return {
    sequence,
    date,
    txnDate: date,
    valueDate,
    particulars: narration || "TRANSACTION",
    chequeNo: chequeItem ? clean(chequeItem.text) : null,
    withdrawal: amountItem && isDebit ? Math.abs(amountItem.value) : null,
    deposit: amountItem && !isDebit ? Math.abs(amountItem.value) : null,
    balance: balanceItem ? roundMoney(balanceItem.value) : null,
  };
}

function shouldKeepWrappedLineBreak(particulars, continuation) {
  return (
    continuation.startsWith("/") ||
    /^DFC\//i.test(continuation) ||
    /^X\d/i.test(continuation)
  );
}

function appendIdbiContinuation(row, line) {
  const continuation = clean(line);
  if (!continuation) return;

  if (shouldKeepWrappedLineBreak(row.particulars, continuation)) {
    row.particulars = `${row.particulars}\r\n${continuation}`;
    return;
  }

  if (/-$/.test(row.particulars)) {
    row.particulars = `${row.particulars}${continuation}`;
    return;
  }

  row.particulars = clean(`${row.particulars} ${continuation}`);
}

function parseBalanceOnlyLine(entry, columns) {
  const balance = amountItems(entry.items || [])
    .filter((item) => item.x >= columns.balance - 30)
    .sort((left, right) => right.x - left.x)[0];
  return balance ? roundMoney(balance.value) : null;
}

function parseIdbiTransactions(lines) {
  const columns = detectAmountColumns(lines);
  const transactions = [];
  let current = null;

  for (let index = 0; index < lines.length; index += 1) {
    const entry = lines[index];
    const text = clean(entry.text || entry);
    if (!text) continue;

    if (isRowStart(entry)) {
      const row = parseIdbiRow(entry, columns);
      if (!row) continue;

      if (row.balance === null) {
        const nextBalance = parseBalanceOnlyLine(lines[index + 1] || {}, columns);
        if (nextBalance !== null) {
          row.balance = nextBalance;
          index += 1;
        }
      }

      transactions.push(row);
      current = row;
      continue;
    }

    if (current && isTerminalLine(text)) {
      current = null;
      continue;
    }

    if (!current || isNoise(text)) continue;
    if (parseBalanceOnlyLine(entry, columns) !== null && /^-?(?:\d{1,3}(?:,\d{2,3})+|\d+)\.\d{1,2}$/.test(text)) {
      continue;
    }

    appendIdbiContinuation(current, text);
  }

  return correctDebitCreditByBalance(transactions).map((row) => {
    const { sequence, ...transaction } = row;
    return transaction;
  });
}

export { isIdbiLayout, parseIdbiTransactions };
